### ISSUE TITLE
colours seem to float around when scrolling when editing file

### ISSUE THREAD

**Issue by lexbi** [abe33/atom-color-highlight#95] opened 2015-06-12 13:08 UTC
http://cl.ly/3n0t0k3E0w1S

It's like they're position:fixed or something like that.

Sorry if this is a dupe, couldn't see anything.

**Comment by abe33** [comment] 2015-06-12 14:24
It's a duplicate of #94, but no worry. As I explain there, this package as well as `project-palette-finder` have been deprecated in favor of [pigments](http://atom.io/packages/pigments). You'll get the same features, but with better performances and a better support for less/sass/scss/stylus functions.

**Closed by abe33** 2015-06-12 14:24 UTC

**Comment by lexbi** [comment] 2015-06-12 14:28
ah thank you!
