### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by izuzak** [abe33/atom-color-highlight#61] opened 2014-12-15 12:29 UTC
_From @francisbautista on December 14, 2014 14:18_

Uncaught TypeError: undefined is not a function

**Atom Version**: 0.154.0
**System**: linux 3.13.0-39-generic
**Thrown From**: [atom-color-highlight](https://github.com/abe33/atom-color-highlight) package

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /home/francis/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:51

TypeError: undefined is not a function
  at MarkerView.module.exports.MarkerMixin.getScope (/home/francis/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:51:81)
  at MarkerView.module.exports.MarkerMixin.hiddenDueToComment (/home/francis/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:55:14)
  at MarkerView.module.exports.MarkerMixin.hidden (/home/francis/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:45:6)
  at MarkerView.module.exports.MarkerView.updateDisplay (/home/francis/.atom/packages/atom-color-highlight/lib/marker-view.coffee:29:17)
  at MarkerView.updateDisplay (/home/francis/.atom/packages/atom-color-highlight/lib/marker-view.coffee:1:1)
  at atom-text-editor.<anonymous> (/home/francis/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:27:63)
  at atom-text-editor.handler (/opt/atom/resources/app/src/space-pen-extensions.js:112:34)
  at atom-text-editor.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:156:19)
  at TextEditorView.jQuery.fn.trigger (/opt/atom/resources/app/src/space-pen-extensions.js:64:23)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/opt/atom/resources/app/src/text-editor-component.js:280:54)
  at CallbackQueue.mixInto.notifyAll (/opt/atom/resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/opt/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
  at /opt/atom/resources/app/src/text-editor-component.js:320:28

```

_Copied from original issue: atom/atom#4609_

**Comment by michaeljcalkins** [comment] 2015-01-14 21:37
```
Uncaught TypeError: undefined is not a function
/c:/Users/Michael%20J.%20Calkins/.atom/packages/atom-color-highlight/lib/marker-element.coffee:81
Hide Stack Trace
TypeError: undefined is not a function
  at color-marker.module.exports.MarkerElement.appendRegion (c:\Users\Michael J. Calkins\.atom\packages\atom-color-highlight\lib\marker-element.coffee:45:26)
  at color-marker.module.exports.MarkerElement.updateDisplay (c:\Users\Michael J. Calkins\.atom\packages\atom-color-highlight\lib\marker-element.coffee:31:8)
  at c:\Users\Michael J. Calkins\.atom\packages\atom-color-highlight\lib\marker-mixin.coffee:35:61
  at Emitter.module.exports.Emitter.emit (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:114:32
  at c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\emissary\lib\emitter.js:155:30
  at Array.forEach (native)
  at Behavior.module.exports.Emitter.emitSlow (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\emissary\lib\emitter.js:154:47)
  at Behavior.module.exports.Emitter.emit (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\emissary\lib\emitter.js:107:30)
  at Behavior.module.exports.Behavior.emit (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\emissary\lib\behavior.js:44:38)
  at Behavior.module.exports.Signal.emitValue (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\emissary\lib\signal.js:82:19)
  at DisplayBuffer.module.exports.Model.set (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\theorist\lib\model.js:166:21)
  at DisplayBuffer.accessor.set (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\theorist\lib\model.js:57:23)
  at DisplayBuffer.module.exports.DisplayBuffer.setScrollTop (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\display-buffer.js:466:31)
  at TextEditor.module.exports.TextEditor.setScrollTop (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:2875:33)
  at [object Object].module.exports.React.createClass.onMouseWheel (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor-component.js:721:16)
  at HTMLDivElement.boundMethod (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\react-atom-fork\lib\ReactCompositeComponent.js:1295:21)
The error was thrown from the atom-color-highlight package This issue has already been reported.
```

**Comment by zephraph** [comment] 2015-01-16 01:04
This happens to me occasionally and when it does it makes Atom completely unusable. After the first instance it happens every 10 to 15 seconds and locks up Atom for a few minutes.

**Comment by abe33** [comment] 2015-01-16 08:33
And is it systematic or is it bound to a context (a specific file, a specific project)? 
I haven't experienced that once so I'll need more details about the issue.

**Comment by zephraph** [comment] 2015-01-16 14:00
I'm not certain. I've removed the plugin for now, but after I'll reinstall it and try it again later. See if I can work out exactly what's causing the problem.

**Comment by tm1000** [comment] 2015-01-16 23:19
@abe33 Its bound to a specific file

This is an example of a file that will do it: https://raw.githubusercontent.com/FreePBX/framework/master/amp_conf/htdocs/admin/libraries/utility.functions.php

**Comment by y-takey** [comment] 2015-01-22 06:27
This happens to write CSS in haml.

e.g.
```haml
%body

:css
  body {
    background-color: #ffffff;
  }
```

**Comment by abe33** [comment] 2015-01-22 08:35
@tm1000 & @y-takey: I can't reproduce this with your two examples, is there some specific steps that leads to this errors? Is it that the buffer is opened at startup? Is it when you open the file? 
The more details the better ;).

**Comment by caffeinewriter** [comment] 2015-01-23 00:04
Personally, this error was thrown while I was moving the pointer by clicking.

**Comment by lucasmotta** [comment] 2015-01-28 12:16
Same as @caffeinewriter. It doesn't happen on any specific piece of code, but when moving the cursor around and clicking/selecting.

**Comment by Jacob-Mischka** [comment] 2015-01-29 19:09
I just had the issue happen to me as well. [These few lines](https://gist.github.com/anonymous/b87e6e4f50e45ecacd76) are all that I had written so far. I added the color code using the [color-picker](https://atom.io/packages/color-picker) package, and atom-color-highlight wouldn't even let me add a semicolon afterward, trying to type anything would result in the error popup.

**Comment by k2trf** [comment] 2015-02-06 20:54
I have experienced this issue today as well, while editing http://pinecrestpark.com/rv.html (a local copy, but was re-uploaded after); this issue made atom unusable for editing this file, and I had to use a different program.

The error would not be thrown until I opened that file and started scrolling down the page (but it was almost immediate upon scrolling). Disabling the plugin (atom-color-highlight) did not stop this error, even after reloading (and completely restarting atom when reloading didn't work).

**Comment by maximilianmikus** [comment] 2015-02-09 13:08
same as @k2trf 

+1

atom version: 0.169.0
node version: 0.10.35

**Comment by caffeinewriter** [comment] 2015-02-09 19:19
Updating to the latest version of Atom seems to fix the issue :)

**Comment by MarkWissler** [comment] 2015-02-26 15:19
I was getting this error. I updated to atom `v0.184.0` and it started working.

**Comment by abe33** [comment] 2015-02-26 15:54
It's probably time I close this issue then.

**Closed by abe33** 2015-02-26 15:54 UTC
